# Generated by Django 5.0.2 on 2024-02-24 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logueo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
